---
title: "The Visual Display of Likert Data"
author: "Jason Bryer"
output: rmarkdown::html_vignette
bibliography:  REFERENCES.bib
abstract: The Likert (Likert, 1932) item format has become the defacto standard in survey research. In the most common format of Likert-items, respondents rate their agreement with a statement from strongly disagree to strongly agree, usually with four to seven levels. Rensis Likert assumed that the distance between each response category are equal, and as such, analysis has typically treated the responses to Likert-items as continuous variables. However, this assumption often does not hold (see e.g. Wakita et al., 2012), although can often easily be verified with the use of visualizations. This paper introduces the likert package that provides a set of functions for analyzing Likert-items, visualizing results using the ggplot2 (Wickham, 2009) package, and reporting results with the xtable (Dahl, 2012) package.
vignette: >
  %\VignetteIndexEntry{The Visual Display of Likert Data}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(likert)
```


The Likert scale was first introduced by Rensis Likert in 1932 [@Likert1932] and has become a widely used for assessment and survey designs.



```{r}
data(pisaitems)
items24 <- pisaitems[,substr(names(pisaitems), 1,5) == 'ST24Q']
head(items24); ncol(items24)

names(items24) <- c(
	ST24Q01="I read only if I have to.",
	ST24Q02="Reading is one of my favorite hobbies.",
	ST24Q03="I like talking about books with other people.",
	ST24Q04="I find it hard to finish books.",
	ST24Q05="I feel happy if I receive a book as a present.",
	ST24Q06="For me, reading is a waste of time.",
	ST24Q07="I enjoy going to a bookstore or a library.",
	ST24Q08="I read only to get information that I need.",
	ST24Q09="I cannot sit still and read for more than a few minutes.",
	ST24Q10="I like to express my opinions about books I have read.",
	ST24Q11="I like to exchange books with my friends.")
```

```{r}
l24 <- likert(items24)
l24
```


```{r}
summary(l24)
```

```{r, out.width='100%', fig.width=8, fig.height=4}
plot(l24)
```


```{r}
l24g <- likert(items24[,1:6], grouping=pisaitems$CNT)
print(l24g)
summary(l24g)
```

```{r, out.width='100%', fig.width=6, fig.height=6}
plot(l24g)
```